### ISSUE TITLE
Grunt parser doesn't work

### ISSUE THREAD

**Issue by rudolfkral** [bdfhjk/VIPER#45]
``` bash
Running "execute:compileParser" (execute) task
-> executing src/backend/parser/Make.js
net.js:164
        throw errnoException(err, 'setBlocking');
              ^
Error: setBlocking ENOSYS
    at exports._errnoException (util.js:746:11)
    at new Socket (net.js:164:15)
    at createWritableStdioStream (node.js:463:18)
    at process.stdout (node.js:502:16)
    at console.js:111:37
    at NativeModule.compile (node.js:805:5)
    at Function.NativeModule.require (node.js:774:18)
    at node.js:214:27
    at Object.<anonymous> (node_modules/jison/lib/jison.js:20:20)
    at Module._compile (module.js:460:26)
Warning: -> error 1 src/backend/parser/Make.js (948ms) Use --force to continue.

Aborted due to warnings.
```

**Comment by chaser92** [comment]
Are you sure? Looks like it's a problem with your machine...

**Comment by rudolfkral** [comment]
It is caused by the lack of src/parser directory structure in dist folder. It is pretty much useless anyways, since the resulting ansic.js is wrapped in "define" function and thus can't be used directly from command line.

**Comment by chaser92** [comment]
I wouldn't say it's useless... it's used by the frontend.

2015-04-21 11:42 GMT+02:00 Adrian Rudolf Kral notifications@github.com:

> It is caused by the lack of src/parser directory structure in dist folder.
> It is pretty much useless anyways, since the resulting ansic.js is wrapped
> in "define" function and thus can't be used directly from command line.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdfhjk/VIPER/issues/45#issuecomment-94722684.

## 

Pozdrawiam,
Mariusz Kierski
